# Generated by Django 5.0.4 on 2024-05-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroNutrientApp', '0002_fooditem_meal_mealentry_meal_fooditems_meallog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealentry',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fooditems',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='meal',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='MealEntry',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealLog',
        ),
    ]
