# Generated by Django 5.0.4 on 2024-06-01 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroNutrientApp', '0010_mealentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroNutrientApp.register'),
        ),
    ]
