# Generated by Django 5.0.4 on 2024-06-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroNutrientApp', '0011_alter_mealentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
