# Generated by Django 5.0.4 on 2024-06-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroNutrientApp', '0013_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealEntry',
        ),
    ]
