# Generated by Django 5.0.4 on 2024-06-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroNutrientApp', '0014_delete_mealentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroNutrientApp.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroNutrientApp.register')),
            ],
        ),
    ]
