# Generated by Django 5.0.4 on 2024-06-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroNutrientApp', '0017_alter_mealentry_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalSetting',
        ),
    ]
