# Generated by Django 5.0.4 on 2024-06-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroNutrientApp', '0019_goalsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
